export const stkVariableClarinet = "clair";
export const stkIdentifierClarinet = "Clarinet";

const clarinetPresets = { // .clair
    reed: {
        name: "reed",
        label: "Reed",
        value: 0.36,
        min: 0.01,
        max: 1.0,
        screenInterface: "knob",
        fxType: "stk",
        type: "float",
    },
    noiseGain: {
        name: "noiseGain",
        label: "Noise Gain",
        value: 0.1,
        min: 0.01,
        max: 1.0,
        screenInterface: "knob",
        fxType: "stk",
        type: "float",
    },
    pressure: {
        name: "pressure",
        label: "Pressure",
        value: 0.36,
        min: 0.01,
        max: 1.0,
        screenInterface: "knob",
        fxType: "stk",
        type: "float",
    },
    rate: {
        name: "rate",
        label: "Rate",
        value: 0.42,
        min: 0.01,
        max: 2.0,
        screenInterface: "knob",
        fxType: "stk",
        type: "float",
    }, // rate in seconds
    vibratoFreq: {
        name: "vibratoFreq",
        label: "Vibr Freq",
        value: 10,
        min: 0,
        max: 1000,
        screenInterface: "knob",
        fxType: "stk",
        type: "int",
    }, // freq in hZ
    vibratoGain: {
        name: "vibratoGain",
        label: "Vibr Gain",
        value: 0.01,
        min: 0.01,
        max: 1.0,
        screenInterface: "knob",
        fxType: "stk",
        type: "float",
    },
    startBlowing: {
        name: "startBlowing",
        label: "Strt Blow",
        value: 1.0,
        min: 0.01,
        max: 1.0,
        screenInterface: "knob",
        fxType: "stk",
        type: "float",
    },
    stopBlowing: {
        name: "stopBlowing",
        label: "Stp Blow",
        value: 0.5,
        min: 0.01,
        max: 1.0,
        screenInterface: "knob",
        fxType: "stk",
        type: "float",
    },
    gain: {
        name: "gain",
        label: "Gain",
        value: 0.3,
        min: 0.01,
        max: 1.0,
        screenInterface: "knob",
        fxType: "stk",
        type: "float",
    },
    // reverb: {
    //     name: "reverb",
    //     label: "Reverb",
    //     value: 5,
    //     min: 0,
    //     max: 100,
    //     screenInterface: "knob",
    // }, // reverb amount (0-100)
};

export default clarinetPresets;