export const data = {
    nodes: [
        { id: "Gain", group: 3 },
        { id: "NRev", group: 1 },
        { id: "DelayL", group: 1 },
        { id: "Chor", group: 'team1' },
        { id: "Modulo", group: 'team2' },
        { id: "ExpEnv", group: 'team2' },
        { id: "PRCRev", group: 'team2' },
        { id: "ExpDelay", group: 'team2' },
        { id: "Bitcrusher", group: 'team3' },
        { id: "PitchTrack", group: 'team3' },
        { id: "Sitar", group: 'team3' },
        { id: "GVerb", group: 'team3' },
        { id: "FileInput", group: 'team3' },
        { id: "Sigmund", group: 'team3' },
    ],
    links: [
        { source: "Gain", target: "GVerb", value: 1 },
        { source: "NRev", target: "DelayL", value: 1 },
        { source: "DelayL", target: "NRev", value: 1 },
        { source: "Chor", target: "DelayL", value: 1 },
        { source: "Modulo", target: "Chor", value: 1 },
        { source: "ExpEnv", target: "Modulo", value: 1 },
        { source: "ExpEnv", target: "Osc1", value: 1 },
        { source: "PRCRev", target: "ExpDelay", value: 1 },
        { source: "ExpDelay", target: "Bitcrusher", value: 1 },
        { source: "Bitcrusher", target: "ExpDelay", value: 1 },
        { source: "ExpDelay", target: "PitchTrack", value: 1 },
        { source: "PitchTrack", target: "Osc2", value: 1 },
        { source: "Sitar", target: "PitchTrack", value: 1 },
        { source: "GVerb", target: "Sitar", value: 1 },
    ]
}
